name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 5.0.100
    - name: dotnet info
      run: dotnet --info
    - name: dotnet restore
      run: dotnet restore ./src/JT809.Protocol.sln
    - name: dotnet build
      run: dotnet build ./src/JT809.Protocol.Test/JT809.Protocol.Test.csproj
    - name: dotnet test
      run: dotnet test ./src/JT809.Protocol.Test/JT809.Protocol.Test.csproj
